<a href="https://colab.research.google.com/github/asegura4488/CienciaDatos/blob/main/Semana1/Sesion2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [71]:
# Cómo generalizamos el concepto de variable?

# Quizá necesitamos un conjunto de variables (sin desconexion)
import numpy as np
Nombre1 = ''
Nombre2 = ''

In [72]:
Lista1 = []
type(Lista1)

list

In [73]:
# Método que mida su longitud
len(Lista1)

0

In [74]:
# Método que incluya nuevos elementos
Lista1 = []
Lista1.append(1)
Lista1.append(3)
Lista1.append(6.5)
Lista1.append(4)
Lista1.append(9.81)

In [75]:
Lista1

[1, 3, 6.5, 4, 9.81]

In [76]:
# Acceder a los datos?
dim = 1*len(Lista1)
dim

5

In [77]:
# En orden canonica de izquierda a derecha
Lista1[1]

3

In [78]:
Lista1[-1]

9.81

In [79]:
Lista1[-2]

4

In [80]:
# Necesitamos estableces una mascara (filtro)!
Lista1[1:4] # los : dentro de una lista es slicing
# Estamos tomando las posiciones 1,2,3

[3, 6.5, 4]

In [81]:
# Queremos tomar los ultimos dos datos
Lista1[-2:]
#Es equivalente a :
#Lista1[3:5]

[4, 9.81]

In [82]:
# Si queremos seleccionar indices especificos
indices = [0,2,4]

# loop comprension
listafiltrada = [ Lista1[i] for i in indices ]
listafiltrada

[1, 6.5, 9.81]

In [83]:
Lista1

[1, 3, 6.5, 4, 9.81]

In [84]:
# Cómo obtengo un "muestra" según algun valor??
#Valores mayores a 2?

In [85]:
Mayores2 = [ x for x in Lista1 if x > 2] # Filtrado numerico
Mayores2

[3, 6.5, 4, 9.81]

In [86]:
Lista1 = np.array(Lista1)
Lista1 > 2

array([False,  True,  True,  True,  True])

In [87]:
Mayores2_2 = Lista1[ Lista1 > 2 ]
Mayores2_2

array([3.  , 6.5 , 4.  , 9.81])

In [89]:
# Quiero filtrar la informacion para valores mayores a 2 y menores que 7
mayores2_7 = [ x for x in Lista1 if 7 > x > 2 ]
mayores2_7

[np.float64(3.0), np.float64(6.5), np.float64(4.0)]

In [90]:
Lista1 > 2

array([False,  True,  True,  True,  True])

In [91]:
Lista1 < 7

array([ True,  True,  True,  True, False])

In [98]:
(Lista1 > 2) & (Lista1 < 7)

array([False,  True,  True,  True, False])

In [97]:
Lista1[ (Lista1 > 2) & (Lista1 < 7) ]

array([3. , 6.5, 4. ])

In [99]:
# Queremos valores mayores que 9 y menores que 7

In [100]:
Lista1

array([1.  , 3.  , 6.5 , 4.  , 9.81])

In [101]:
(Lista1 > 9) & (Lista1 < 7)

array([False, False, False, False, False])

In [102]:
# Y si queremos O
(Lista1 > 9) | (Lista1 < 7)

array([ True,  True,  True,  True,  True])

In [103]:
Lista1[ (Lista1 > 9) | (Lista1 < 7) ]

array([1.  , 3.  , 6.5 , 4.  , 9.81])

In [106]:
# Una ultima forma de filtrar
np.where(Lista1 > 6)

(array([2, 4]),)

In [107]:
# Una ultima forma de filtrar
def EscogerEdad(x):
  return x > 7

In [108]:
ListaMenores = list( filter(EscogerEdad,Lista1) )
ListaMenores

[np.float64(9.81)]

# Calles y Carreras -> Matrices -> Hoja de calculo
## Matriz sea una lista de listas

In [130]:
Matriz = [[4,5],[3,2],[5,9]]
type(Matriz)

list

In [131]:
Matriz

[[4, 5], [3, 2], [5, 9]]

In [132]:
Matriz[0]

[4, 5]

In [133]:
Matriz[1]

[3, 2]

In [134]:
Matriz

[[4, 5], [3, 2], [5, 9]]

In [137]:
# Como iteramos este nuevo objeto ("Accesibilidad")
for i in range(3):

  if i == 0:
    print('Calle ',Matriz[i])
    for j in range(2):
      print(Matriz[i][j])
  elif i == 1:
    print('Calle ',Matriz[i])
    for j in range(2):
      print(Matriz[i][j])
  elif i == 2:
    print('Calle ',Matriz[i])
    for j in range(2):
      print(Matriz[i][j])

Calle  [4, 5]
4
5
Calle  [3, 2]
3
2
Calle  [5, 9]
5
9


In [138]:
Matriz = np.array(Matriz)
Matriz

array([[4, 5],
       [3, 2],
       [5, 9]])

In [142]:
# Guardamos la informacion
np.savetxt('Datos.csv',Matriz,delimiter=',',newline='\n')

In [143]:
# Necesitamos habilitar colab
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


In [157]:
import os
!ls

Datos  Datos.csv  new.csv  Semana1


In [152]:
os.chdir('/content/drive/MyDrive/ColabNotebooks/Cursos/CursoCienciaDatos')

In [153]:
!ls

Datos  new.csv	Semana1


In [154]:
# Guardamos la informacion
np.savetxt('Datos.csv',Matriz,delimiter=',',newline='\n')

In [155]:
from google.colab import files
files.download('Datos.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>